#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#----------------------------------------#
#            	 ALIASES                 #
#----------------------------------------#

alias lsa='ls -a'
alias p='sudo pacman'
alias cls='clear'
alias config='nvim ~/.config/i3/config'

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

#----------------------------------------#
#           STARTUP COMMANDS             #
#----------------------------------------#

